import "./styles/globals.css";
import Head from "next/head" //como retorno do export default function App({ Component, pageProps}){
import Header from '../components/Header';
import Footer from '../components/Footer';


export default function App({ Component, pageProps}){

    return (
	<>
	    <Head>
	        <title> Munnin | The Observed Knowledge </title>
            <meta
                name="description"
                content="Generated by next"
            />
            <meta
                name="viewport"
                content="width=device-width, initial-scale=1"
            />
            <link rel="icon" href="/favicon.ico" />
            <link rel="preconnect" href="https://fonts.googleapis.com" />
            <link
                rel="preconnect"
                 href="https://fonts.gstatic.com"
                crossOrigin="true"
            />
            <link
                href="https://fonts.googleapis.com/css2?family=Oswald:wght@200;300;400;500;600;700;0,800;0,900;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&display=swap"
                rel="stylesheet"
                />
        </Head>
	<Header />
	<Component {...pageProps} />
	<Footer />
	</>
	);
}


